### PR TITLE
Feature/add poetry

### PR DESCRIPTION
**Pull request by white-gecko**
Use poetry (https://python-poetry.org/) for dependency management.

### CODE REVIEW

**Review by splattater — CHANGES_REQUESTED** [review]
Poetry itself is working I guess. I created a virtual environment (virtualenvwrapper) and used 
```poetry install```.

First tests for test_app.py failed with

```
Ran 81 tests in 3.677s

FAILED (failures=4, errors=3, skipped=5)
```

I can run the store and a SELECT query worked as intended. Maybe I have a dependeny problem with my local python 3.9.5.
It might be useful to update the install section of README.md for poetry usage.

**Comment by white-gecko** [comment]
Could you please check again. It was mostly as assumed by you, the master/main issue.

**Comment by splattater** [comment]
Fixed one more failing test (test_core.py), but there a still many tests not working at the moment.

test_conf.py
Ran 11 tests in 0.054s
FAILED (failures=6)

test_git.py
Ran 36 tests in 8.193s
FAILED (errors=9, skipped=2)

test_endpoint.py
Ran 4 tests in 0.251s
FAILED (failures=1)

test_git.py
Ran 36 tests in 3.142s
FAILED (errors=9, skipped=2)

**Comment by white-gecko** [comment]
The tests pass on the CI. The tests fail due the the setting:
```
[init]
        defaultBranch = main
```

As it was clear to us already.
So I suggest to handle this in a separate issue and pr: #294
So we should be able to merge this one. Is this ok for you @splattater ?

**Pull request merged**
