### PR TITLE
Update GitRepo to use pygit2

### PR DESCRIPTION
**Pull request by splattater**
This commit changes the git library from GitPython to pygit2.
With this commit the installation of QuitStore changes and libgit2 is needed to fulfill the requirements of pygit2.

### CODE REVIEW

**Comment by white-gecko** [comment]
The `quit.log` is also commited and thus my verification script fails.

**Comment by splattater** [comment]
I added an option to enable "pathspec" in pygit2 when using the index_add_all method.
The method will be called with a list containing all files that are configured in config.ttl, so every unknown/untracked files won't be added to index.
You could also update your gitignore to avoid that issue.

**Comment by white-gecko** [comment]
With `--pathspec` option it creates empty commits.

**Comment by white-gecko** [comment]
https://github.com/AKSW/QuitEval/blob/master/verify.py: OK

**Pull request merged**
