### PR TITLE
Add octicons to quit.spec to include in pyinstaller

### PR DESCRIPTION
**Pull request by white-gecko**
Add octicons to quit.spec to be included in pyinstaller bundles.

### CODE REVIEW

**Comment by white-gecko** [comment]
Have you tried building it with pyinstaller? For me this fixes the images to be loaded.

**Comment by splattater** [comment]
Yes. I tried it again and uses a private tab and I can reproduce it.
I'm using `pyinstaller -F quit.spec` and `dist/run -t /my/repo -vv -f provenance`

**Comment by white-gecko** [comment]
Sorry I've forgotten a sub directory.

**Comment by splattater** [comment]
OK, it's working now.

**Comment by white-gecko** [comment]
@white-gecko will you merge it?

**Pull request merged**
