### PR TITLE
Accept queries according to SPARQL 1.1 Protocol §2.1 and §2.2

### LINKED ISSUE #113: Fully support SPARQL 1.1 Protocol Operations
We should fully support the SPARQL 1.1 Protocol Operations: https://www.w3.org/TR/sparql11-protocol/#protocol

Currently we accept 

the following GET request:

    curl http://localhost:5000/sparql\?query=INSERT%20DATA%20%7B%20GRAPH%20%3Chttp%3A%2F%2Fexample.org%2F%3E%20%7B%20%3Curn%3Aa%3E%20%3Curn%3Ab%3E%20%3Curn%3Ac%3E%20%7D%7D

and the following POST requests

    curl -d 'query=INSERT DATA { GRAPH <http://example.org/> { <urn:a> <urn:b> <urn:c> }}' http://localhost:5000/sparql
    curl -d 'query=INSERT%20DATA%20%7B%20GRAPH%20%3Chttp%3A%2F%2Fexample.org%2F%3E%20%7B%20%3Curn%3Aa%3E%20%3Curn%3Ab%3E%20%3Curn%3Ac%3E%20%7D%7D' http://localhost:5000/sparql

I don't know, which Content-Type is sent in these cases.

But we don't accept:

    curl -d 'INSERT DATA { GRAPH <http://example.org/> { <urn:a> <urn:b> <urn:c> }}' -H "Content-Type: application/sparql-query" http://localhost:5000/sparql

### PR DESCRIPTION
**Pull request by white-gecko**
Fix #113 .

- [x] Add tests
- [x] rebase
- [x] update README

### CODE REVIEW

**Comment by white-gecko** [comment]
@splattater please review and merge if tests are successful

**Comment by white-gecko** [comment]
@splattater I don't think it is a good idea to return UnSupportedQueryType if a query just had no effect. If we want to make changes to the API here we should do this in another branch.

**Comment by splattater** [comment]
I think the store will be updated but the files won't. I will check this.

**Comment by splattater** [comment]
You are right @white-gecko, there won't be an effect. I will merge.

**Pull request merged**
